
server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #create
    show-sql: true