server:
  port: 9595

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MnDb?createDatabaseIfNotExist=true
    username: root
    password: en
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
